const sections=[...document.querySelectorAll('main section')],dots=document.getElementById('dots');let current=0;
sections.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',i===0?'Capa':'Capítulo '+i);b.onclick=()=>go(i);dots.append(b)});
function go(i){sections[Math.max(0,Math.min(sections.length-1,i))].scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){current=sections.indexOf(e.target);document.getElementById('counter').textContent=String(current).padStart(2,'0')+' / 09';[...dots.children].forEach((d,i)=>d.setAttribute('aria-current',String(i===current)));document.getElementById('prev').disabled=current===0;document.getElementById('next').disabled=current===9;}})},{rootMargin:'-25% 0px -35% 0px',threshold:0});sections.forEach(s=>observer.observe(s));document.getElementById('prev').onclick=()=>go(current-1);document.getElementById('next').onclick=()=>go(current+1);
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|BUTTON|SUMMARY/.test(e.target.tagName))return;if(['ArrowRight','PageDown'].includes(e.key)){e.preventDefault();go(current+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}});
document.getElementById('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{document.getElementById('full').textContent='Indisponível neste navegador'}};
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-answer]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.getElementById('feedback').textContent=b.dataset.answer==='b'?'Isso: a mensagem B usa urgência. “Última chance” pressiona a decisão sem acrescentar uma característica do produto.':'A mensagem A informa uma característica verificável. É a B que usa urgência para tentar acelerar a escolha.'});
// Geometria abstrata projetada em 3D: cada capítulo altera o campo visual.
const canvas=document.getElementById('scene'),ctx=canvas.getContext('2d');let w=0,h=0,t=0,px=0,py=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,last=0;const motion=document.getElementById('motion');
function motionLabel(){motion.textContent=paused?'Ativar movimento':'Pausar movimento';motion.setAttribute('aria-pressed',String(paused))}motionLabel();motion.onclick=()=>{paused=!paused;motionLabel()};addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5)*.25;py=(e.clientY/innerHeight-.5)*.2});
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio,1.5);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function render(now){requestAnimationFrame(render);if(now-last<33)return;last=now;if(document.hidden)return;if(!paused)t+=.006;ctx.fillStyle='#08090c';ctx.fillRect(0,0,w,h);const progress=scrollY/Math.max(1,document.documentElement.scrollHeight-h),ang=t+progress*3.2,scale=Math.min(w,h)*.30,cx=w*(w<700?.65:.73),cy=h*.46;
const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,scale*2);glow.addColorStop(0,'#20324755');glow.addColorStop(1,'#08090c00');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
const project=(a,b)=>{const r=1+.20*Math.sin(3*a+progress*8)*Math.cos(2*b);let x=r*Math.sin(b)*Math.cos(a),y=r*Math.cos(b),z=r*Math.sin(b)*Math.sin(a);const x1=x*Math.cos(ang)-z*Math.sin(ang),z1=x*Math.sin(ang)+z*Math.cos(ang);const tilt=.4+(paused?0:py);const y1=y*Math.cos(tilt)-z1*Math.sin(tilt),z2=y*Math.sin(tilt)+z1*Math.cos(tilt);const k=3/(3+z2);return[cx+(x1+(paused?0:px))*scale*k,cy+y1*scale*k,z2]};
for(let j=1;j<28;j++){ctx.beginPath();let depth=0;for(let i=0;i<=100;i++){const p=project(i/100*Math.PI*2,j/28*Math.PI);if(i===0)ctx.moveTo(p[0],p[1]);else ctx.lineTo(p[0],p[1]);depth+=p[2]}ctx.strokeStyle=j%7===0?'#a5bed055':'#839bae28';ctx.lineWidth=j%7===0?1.3:.6;ctx.stroke()}
for(let j=0;j<26;j++){ctx.beginPath();for(let i=0;i<=70;i++){const p=project(j/26*Math.PI*2,i/70*Math.PI);if(!i)ctx.moveTo(p[0],p[1]);else ctx.lineTo(p[0],p[1])}ctx.strokeStyle='#91adc42c';ctx.lineWidth=.7;ctx.stroke()}
for(let i=0;i<28;i++){const a=i*2.39996,p=project(a,(i+.5)/28*Math.PI);ctx.fillStyle=i%7===0?'#ff524e':'#c5dced88';ctx.beginPath();ctx.arc(p[0],p[1],i%7===0?2.6:1.2,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#c7d5e522';for(let i=0;i<45;i++){const x=((i*179.71)%1000)/1000*w,y=((i*279.13)%997)/997*h;ctx.fillRect(x,y,1,1)}}requestAnimationFrame(render);
